flickmatch/home

platform/README.md, platform/src/main/java/com/flickmatch/platform/graphql/builder/EventBuilder.java, platform/src/main/java/com/flickmatch/platform/graphql/type/Event.java, platform/src/main/resources/graphql/schema.graphqls
tested query, added response below: 
{
"data": {
"city": {
"cityId": "1",
"cityName": "Gurgaon",
"events": [
{
"displayId": "04-13-1",
"displayTitle": "7v7 Thu, Apr 13 11:00AM-12:00PM Gallant play arena south City 1",
"venueLocationLink": "https://maps.app.goo.gl/ebEXAjXrsUvBanyY9",
"charges": 200.0,
"reservedPlayersList": [],
"waitListPlayers": [],
"date": "Thu, Apr 13",
"time": "11:00AM-12:00PM",
"venueName": "Gallant play arena south City 1",
"reservedPlayersCount": 14,
"waitListPlayersCount": 5
}
]
}
}
}
=> Add individual fields in Event and validation

whatsapp-js/src/parseUsualQueue.js, whatsapp-js/test/parseUsualQueueTest.js
isSuccessful could be used for Queue message detection
=> add isSuccessful to parseUsualQueueTest

video-analytics-main/scripts/data_generation.py
Creating an interface for data generation pipeline.
=> Adding Data Generation Interface

highlights-ml/scripts/data_generation.py
PR to fill out the functions added last time. This reads the structured labelled data from spreadsheet regarding goals during a particular match and saves those frames as positives for a binary classification model. 
@shivam15668 to write test case.
=> Adding data generation function modules

react-fm/src/pages/matchQueues/Queue.tsx, react-fm/src/pages/matchQueues/data.ts, react-fm/src/pages/matchQueues/eventsComponents/Events.tsx, react-fm/src/pages/matchQueues/types/Events.types.tsx
=> Sumit fm/homepage

StripeWebhook/build.gradle, StripeWebhook/src/main/java/com/flickmatch/webhook/StripeRequestHandler.java, StripeWebhook/src/main/java/com/flickmatch/webhook/graphql/JoinEventResponse.java, StripeWebhook/src/main/java/com/flickmatch/webhook/graphql/client/PlatformGraphQLClient.java, StripeWebhook/src/main/resources/joinEvent.graphql, StripeWebhook/src/test/java/com/flickmatch/platform/StripeRequestHandlerTest.java, StripeWebhook/src/test/resources/event_checkout_complete_sample_payload.json, platform/src/main/java/com/flickmatch/platform/graphql/builder/EventBuilder.java, platform/src/main/java/com/flickmatch/platform/graphql/builder/PlayerBuilder.java, platform/src/main/java/com/flickmatch/platform/graphql/controller/EventController.java, platform/src/main/java/com/flickmatch/platform/graphql/controller/PlayerController.java, platform/src/main/java/com/flickmatch/platform/graphql/mapper/UpdatePlayerListInputMapper.java, platform/src/main/resources/graphql/schema.graphqls, platform/src/test/java/com/flickmatch/platform/graphql/builder/PlayerBuilderTest.java, platform/src/test/java/com/flickmatch/platform/graphql/mapper/UpdatePlayerListInputMapperTest.java
=> Revert "Revert "Stripe webhook setup""

platform/src/main/java/com/flickmatch/platform/bean/confugration/ProxyConfiguration.java, platform/src/main/java/com/flickmatch/platform/dynamodb/model/PaymentRequest.java, platform/src/main/java/com/flickmatch/platform/dynamodb/repository/CityRepository.java, platform/src/main/java/com/flickmatch/platform/dynamodb/repository/PaymentRequestRepository.java, platform/src/main/java/com/flickmatch/platform/graphql/builder/EventBuilder.java, platform/src/main/java/com/flickmatch/platform/graphql/builder/PaymentRequestBuilder.java, platform/src/main/java/com/flickmatch/platform/graphql/controller/PaymentController.java, platform/src/main/java/com/flickmatch/platform/graphql/input/InitiatePaymentInput.java, platform/src/main/java/com/flickmatch/platform/graphql/input/JoinEventInput.java, platform/src/main/java/com/flickmatch/platform/graphql/type/Event.java, platform/src/main/java/com/flickmatch/platform/graphql/type/InitiatePaymentOutput.java, platform/src/main/java/com/flickmatch/platform/proxy/PhonePeProxy.java, platform/src/main/resources/application-beta.properties, platform/src/main/resources/application-dev.properties, platform/src/main/resources/application-prod.properties, platform/src/main/resources/graphql/schema.graphqls, platform/src/test/resources/application-test.properties
- major changes
Flow starts from PaymentController and uses eventBuilder to get the amount for event. Then we call Phonepe to generate link. After that we store data in PaymentRequest table which will be used after getting the call back from phonePe.
- Other changes are some refactoring and creating a new Id to represent event. eventId that we were using earlier didn't had cityId so we have to pass that explicitly.
=> Complete logic to initiate payment

whatsapp-js/src/parseUsualQueue.js
https://stackoverflow.com/questions/11305797/remove-zero-width-space-characters-from-a-javascript-string
=> parse zero width space characters from js.

whatsapp-js/src/notificationRequestParser.js, whatsapp-js/test/notificationRequestParserTest.js
Tested the code using an online compiler after creating two date time stamps. Here are the screenshots for the same.
These timestamps were generated using online tools and were of the date ( 12:00 - 18:00 25-03-2024 (Monday) )
=> Changed the notification time for whatsapp js after successful phone pe payment.

platform/src/main/java/com/flickmatch/platform/graphql/builder/EventBuilder.java, platform/src/main/java/com/flickmatch/platform/records/WhatsAppNotification.java, platform/src/test/java/com/flickmatch/platform/proxy/WhatsAppProxyTest.java, whatsapp-js/main.js, whatsapp-js/src/notificationRequestParser.js, whatsapp-js/test/notificationRequestParserTest.js
Expected format of message according to current code :
HotFut GachiBowli (https://goo.gl/maps/1QzakRkJPHxT8GjRA)
02:14 AM - 03:14 AM
12-11-2023 (Sunday)
5v5
₹200/- Per Person.
Confirmed Players:
Player1
Player2
sam
nooo
Please pay at (https://play.flickmatch.in/match-queues#1-2024-03-28-1) to confirm your spot.
=> Formatted message

whatsapp-js/src/notificationRequestParser.js, whatsapp-js/test/notificationRequestParserTest.js
Flickmatch football game at HotFut GachiBowli 📍 (https://goo.gl/maps/1QzakRkJPHxT8GjRA)
🕐 02:14 AM - 03:14 AM 
📅 12/11/2023 (Sunday)
5 🆚 5
₹200/- Per Person.
🎫 Confirmed Players:
1. Player1
2. Player2
3. sam
4. nooo
Please pay 💵 at (https://play.flickmatch.in/match-queues#1-2024-03-28-1) to confirm your spot.
=> Formatted the message and added icons.

platform/src/main/java/com/flickmatch/platform/graphql/builder/EventBuilder.java
=> changed event expiry to 48 hours

platform/src/main/java/com/flickmatch/platform/graphql/builder/EventBuilder.java
=> Revert "changed event expiry to 48 hours"

react-fm/package-lock.json, react-fm/package.json, react-fm/src/Root.tsx, react-fm/src/pages/addGame/AddGame.tsx, react-fm/src/pages/adminPage/AdminPage.tsx, react-fm/src/pages/googleLoginAuth/GoogleLogin.module.scss, react-fm/src/pages/googleLoginAuth/GoogleLogin.tsx, react-fm/src/pages/matchQueues/eventsComponents/RazorPay.ts, react-fm/src/pages/profile/Profile.tsx
=> Revert "Firebase authentication on new branch"

platform/src/main/java/com/flickmatch/platform/dynamodb/model/Event.java, platform/src/main/java/com/flickmatch/platform/graphql/builder/EventBuilder.java, platform/src/main/java/com/flickmatch/platform/rest/RazorPaymentCallbackController.java, platform/src/test/java/com/flickmatch/platform/graphql/builder/EventBuilderTest.java
=> Revert "Added changes which shows previous day events"

.gitignore, platform/src/main/java/com/flickmatch/platform/dynamodb/model/Event.java, platform/src/main/java/com/flickmatch/platform/dynamodb/repository/EventRepository.java, platform/src/main/java/com/flickmatch/platform/graphql/builder/EventBuilder.java, platform/src/main/java/com/flickmatch/platform/rest/RazorPaymentCallbackController.java, platform/src/test/java/com/flickmatch/platform/graphql/builder/EventBuilderTest.java
=> Revert "Event optimization"

.github/workflows/platform-deploy.yml, .github/workflows/platform-dryrun.yml
Add creation of .env file by fetching values from git secrets as part of platform deployment steps
Setting up secrets as env variables as a deployment step. Secrets need to manually added in github secret store before merging
=> Add .env creation in platform deployment

.github/workflows/platform-deploy.yml, .github/workflows/platform-dryrun.yml
Add " -Dspring.profiles.active=prod " as part of the gradle build step in deploy and dryrun work flow to only build prod profile
=> Update gradle build to only build prod 

.github/workflows/platform-deploy.yml
Add -Dspring.profiles.active=prod in run instead of working directory for gradle build step
=> Fix platform-deploy.yml

.github/workflows/platform-deploy.yml, .github/workflows/platform-dryrun.yml
=> Update platform-deploy.yml to fix workflow step 

react-fm/src/pages/eventPage/EventPage.tsx, react-fm/src/pages/googleLoginAuth/GoogleLogin.tsx, react-fm/src/pages/matchQueues/eventsComponents/JoinNow.tsx
Used location history to reach the same page where it came from after login.
=> Added redirect url after login

react-fm/src/pages/matchQueues/eventsComponents/Events.module.scss, react-fm/src/pages/matchQueues/eventsComponents/Events.tsx, react-fm/src/pages/matchQueues/eventsComponents/JoinNow.tsx, react-fm/src/pages/matchQueues/eventsComponents/Players.tsx
=> Revert "Updating number of players and  price"
